<!DOCTYPE html>
<html>
<body>

<?php



$GLOBALS['app_dictionary'] = array(
  array('Hello', 'Ciao'),
  array('Monday','lunedì'),
  array('Tuesday','martedì'),
  array('Wednesday','mercoledì'),
  array('Thursday','giovedì'),
  array('Friday','venerdì'),
  array('Saturday','sabato'),
  array('Sunday','domenica'),
  array('January', 'gennaio'),
  array('February', 'febbraio'),
  array('March', 'marzo'),
  array('April', 'aprile'),
  array('May', 'maggio'),
  array('June', 'giugno'),
  array('July', 'luglio'),
  array('August', 'agosto'),
  array('September', 'settembre'),
  array('October',  'ottobre'),
  array('November', 'novembre'),
  array('December', 'dicembre'),
  array('Please Login To acces this page','Per favore Login Per accedere a questa pagina'),
  array('No Calendar Found',''),
  array('Booking Calendar',''),
  array('Logout',''),
  array('Setup',''),
  array('Reports',''),
  array('Booking','Prenotazione'),
  array('Reservation Notes',''),
  array('Select the owner of the reservation',''),
  array('You See this Becuase You Are an admin select the user',''),
  array('You',''),
  array('Start at',''),
  array('End at',''),
  array('Period Started at',''),
  array('Close',''),
  array('Confirm Booking',''),
  array('Add new Booking',''),
  array('Pick a Date',''),
  array('This Calendar Has No Years',''),
  array('unexcpted Error Calendar Data Not Loaded',''),
  array('Reservation Status',''),
  array('Pending',''),
  array('Paused',''),
  array('Completed',''),
  array('Update Status',''),
  array('Current slot ID',''),
  array('Current reservation ID',''),
  array('This Calendar Has No Years',''),
  array('unexcpted Error Calendar Data Not Loaded',''),
  array('View Slot',''),
  array('Period Date',''),
  array('Slot Index',''),
  array('start',''),
  array('end',''),
  array('Back',''),
  array('Bootstrap Factory Reset',''),
  array('If you click this button, all bootstrap class style patterns related to',''),
  array('will only be reset and there will be no way back',''),
  array('Reset',''),
  array('Name',''),
  array('Notes',''),
  array('Reservation Owner Data',''),
  array('Username',''),
  array('Email',''),
  array('Role',''),
  array('Edit Reservation',''),
  array('Please Enter a valid name',''),
  array('Description',''),
  array('booking cancellation1','cancellazione della prenotazione'),
  array('Cancel Booking',''),
  array('Are you sure you want to cancel your reservation','Sei sicuro di voler cancellare la prenotazione'),
  array('Select another slot',''),
  array('Change Slot',''),
  array('Home','iniziale'),
  array('Calendars',''),
  array('Add New Calendar',''),
  array('Used',''),
  array('Periods',''),
  array('years',''),
  array('Slots',''),
  array('Remove',''),
  array('Advanced',''),
  array('User Manger',''),
  array('Add New User',''),
  array('ID',''),
  array('Firstname',''),
  array('Active',''),
  array('Actions',''),
  array('Yes',''),
  array('No',''),
  array('Edit',''),
  array('Delete',''),
  array('Please wait',''),
  array('Calendar Title',''),
  array('Calendar Description',''),
  array('Start Year',''),
  array('Years Added',''),
  array('Periods',''),
  array('Periods Per Day',''),
  array('Slots',''),
  array('Slots Per Period',''),
  array('Calendar Logo And Icon',''),
  array('Login and Signup background-image (Optional)',''),
  array('Mange Calendar',''),
  array('Main Info',''),
  array('Calendar Title: (Optional)',''),
  array('Calendar Description: (Optional)',''),
  array('Calendar Logo And Icon (Optional)',''),
  array('Login and Signup background-image (Optional)',''),
  array('Edit Calendar Data',''),
  array('Add More Years',''),
  array('if you leave this input will not effect the original years added',''),
  array('Mange Periods',''),
  array('Mange Slots',''),
  array('Add New Periods',''),
  array('Total Periods',''),
  array('Added periods',''),
  array('Add Periods',''),
  array('Add New Slots',''),
  array('Total Slots',''),
  array('Added Slots',''),
  array('Add Slots',''),
  array('Delete Calendar',''),
  array('Are You Sure You want Delete calendar click Remove Calendar',''),
  array('Remove Calendar',''),
  array('Full Name',''),
  array('Enter User Full Name',''),
  array('Enter User Email',''),
  array('Enter Username',''),
  array('Password',''),
  array('Enter User Password',''),
  array('System Data',''),
  array('User',''),
  array('Admin',''),
  array('if you set this to No the user will not able to login also this used for protected user from invalid passwords accessed limits',''),
  array('Submit',''),
  array('Change Password',''),
  array('Delete User',''),
  array('Are You Sure You want Delete User Click on Remove User',''),
  array('Remove User',''),
  array('Here You can edit every slot index start and end date (1,2,3),(4,5,6),(7,8,9) or even old type (1,2,3),(1,2,3),(1,2,3) so it the core dynamic u can have any order',''),
  array('Error In MySQL Connection at line 18 becuase missing PDO maybe becuase another MySQL server runing on same port so close it first',''),
  array('Go To Setup',''),
  array('Go To Home',''),
  array('Go To Reports',''),
  array('Go To Signup',''),
  array('Go To Login',''),
  array('Warning',''),
  array('Enter password',''),
  array('Remember me',''),
  array('Register',''),
  array('Login','Registrazione'),
  array('Forget Your Password do not worry Click here to reset your password',''),
  array('You Have No Premssion To access This Page',''),
  array('Reservations Per Users',''),
  array('Reservations Per Year',''),
  array('Reservations Per Month',''),
  array('Reservations Per Periods',''),
  array('Perfered Users Periods',''),
  array('Perfered Users Slots',''),
  array('this help you to know the best period and slot in your system merge them if not already merged',''),
  array('Best Period And Slot',''),
  array('Sorry, no used calendar found to display Please add a new calendar and it will be marked as used by default...',''),
  array('No years were found for the specified calendar If u can not solve this add years to calendar or delete the calendar and add new one',''),
  array('We Can not Get the Month Error Error:01',''),
  array('We Can not Get the current Month List make sure calendar setup is valid or try with other calendar Error:02',''),
  array('We Can not Load the current dats of calendar Error Error:03',''),
  array('Reservation Can not Added Invalid Data Sent.',''),
  array('Slot Selected Not Found Reservation Can not Added.',''),
  array('Reservation Can not Added There are a reservation in that slot The System Has recover and fix the problem.',''),
  array('Slot Data Cound not Updated.',''),
  array('Reservation created could not found',''),
  array('Added Reservation Successfully ID:',''),
  array('Reservation Can not Added to the system.',''),
  array('Can not Add reservation missing required data.',''),
  array('Invalid user id please make sure you logged still logged in refresh page',''),
  array('Access Deined',''),
  array('You have no premssions to Make this request',''),
  array('Invalid user id and premsions',''),
  array('The calendar cannot be executed. The procedure is not set up correctly',''),
  array('You Have no access to perform action',''),
  array('Missing Reservation Id Or Next Status refresh page and try again make sure reservation not deleted',''),
  array('Could Not Find that reservation on system refresh page and try again make sure reservation not deleted',''),
  array('No Changed detected',''),
  array('Please login',''),
  array('No premssion to perform action.',''),
  array('Status updated successfully',''),
  array('Could Not Update Status System Crtical error 500.',''),
  array('Status updated successfully.',''),
  array('Could not update reservation data.',''),
  array('Please Login First.',''),
  array('missing required data can not proccess request (Reservation ID)',''),
  array('Can not Find reservation on system make sure it not deleted please refresh the page',''),
  array('Can not Find reservation owner on system make sure it not deleted please refresh the page if not solved contact support',''),
  array('missing required data can not proccess request (current/next slot id)',''),
  array('Sorry you can not perform this type of actions here.',''),
  array('No changes detected',''),
  array('Current Or new reservation owner not found or deleted sorry.',''),
  array('System Crtical Error Missing required Data or Required data not found in system contact Admin',''),
  array('You have no Premessions To edit others Reservations',''),
  array('could not update reservation slot',''),
  array('could not update reservation owner',''),
  array(', could not update reservation owner',''),
  array('Updated Reservation Slot successfully.',''),
  array('Could Not Update Reservation.',''),
  array('Day Date selected Not Avail Calendar Id or Day date invalid Please check other calendar',''),
  array('No calendar Id provided in request make sure you not deleted all calendars from setup and not restart the page yet',''),
  array('Successfully Found Data',''),
  array('can not setup containers bad request',''),
  array('Sorry no Calendar exist you may deleted it from setup page',''),
  array('setup_elements',''),
  array('can not setup elements bad request',''),
  array('done setup elements',''),
  array('can not update style missing Name Or Id of current element',''),
  array('element not found please install it',''),
  array('The select column name provided unkown by the system please add it to database',''),
  array('The select option value provided unkown by the system please add it to the column enum values but you must know BS5 if unkown bs nothing happends.',''),
  array('Updated Container Group',''),
  array('Class',''),
  array('Successfully',''),
  array('unkown error happend',''),
  array('element not found please install it',''),
  array('Updated',''),
  array('Element Data not provided',''),
  array('Updated elements background',''),
  array('Elements bg could not updated',''),
  array('Updated element background',''),
  array('Element bg could not updated',''),
  array('no calendar id sent',''),
  array('Calendar bootstrap classes have been successfully reset',''),
  array('Unable to reset bootstrap style classes To HTML elements found installed in system Try to install the elements first then try again.',''),
  array('unkown request',''),
  array('Reservation Not Found Or Deleted.',''),
  array('Reservation Canceled Successfully',''),
  array('Can not Cancel Reservation',''),
  array('You Have No Premssions To Remove this Reservation',''),
  array('Updated Successfully',''),
  array('You Have no access To edit this reservation',''),
  array('System Error Can not Ge current styles data of this calendar Contact Developer [Periods Styles Missing Recomended (Problem In Add years Periods)]',''),
  array('System Error Can not Ge current styles data of this calendar Contact Developer [Slot Styles Missing Recomended (Problem In Add years Slots)]',''),
  array('Start Year can not be less than 1900 or highr than 5000 selected year is',''),
  array('No Added Years Deatected Added Year must be positve number',''),
  array('Please Prove Calendar Title is required',''),
  array('Warning Your image not Uploaded due to this issue',''),
  array('But calendar Created With default image try to edit the image',''),
  array("No Logo image and registration image uploaded, this is logo and icon and the second is background image for login and registration, you can change default image later","Nessuna immagine del logo e immagine di registrazione caricata, questo è il logo e l'icona e la seconda è l'immagine di sfondo per l'accesso e la registrazione, puoi modificare l'immagine predefinita in un secondo momento"),
  array('Warning Your sign background image not Uploaded due to this issue',''),
  array('But calendar Created With default sign image  try to edit the sign image',''),
  array('No registration image uploaded for website, note that this is a background image for website login and registration, so use your custom image to suit your customers needs as per website customization for better user experience',''),
  array('Unkown Error Calendar Can not setup please edit Configurations and try again',''),
  array('Could not remove Calendar With ID',''),
  array('Removed successful',''),
  array('Calendar Not Found Please Refresh The Page',''),
  array('Successfully removed user with ID',''),
  array('Could not remove the user',''),
  array('User Not Found Please Refresh The Page',''),
  array('User can not added There other User With Same username',''),
  array('User can not added There other User With Same email',''),
  array('Successfully Add user with ID',''),
  array('and Name',''),
  array('can not added',''),
  array('User ID',''),
  array('Updated Successfully Data Updated',''),
  array('Calendar With ID',''),
  array('Marked As Used',''),
  array('Calendar Could not updated try refresh the page',''),
  array('Is Not Found',''),
  array('Could not update the title',''),
  array('Could not update the description',''),
  array('Could not update the background',''),
  array('Could not save new background URL',''),
  array('background_image',''),
  array('Could not update the sign background',''),
  array('Could not save new sign background URL',''),
  array('Update Calendar With ID',''),
  array('Changed',''),
  array('calendar not found or deleted can not update',''),
  array('period Description',''),
  array('period DateTime',''),
  array('No changes were detected',''),
  array('Successfully Update',''),
  array('new slot can not added due to problem in style please contact support',''),
  array('new slot can not added due to problem in current used calendar try change it',''),
  array('Successfully Add',''),
  array('periods to calendar with ID',''),
  array('Invalid slots data, period cannot be added',''),
  array('Slot is not found or delete please refresh the page if problem not solve contact us',''),
  array('Slots to calendar with ID',''),
  array('calendar is not found or delete please refresh the page if problem not solve contact us',''),
  array('The selected Calendar With ID',''),
  array('Has no periods',''),
  array('No periods Found Please restart the page',''),
  array('Not all periods Deleted unkown error',''),
  array('Removed Period With Index:',''),
  array('Total removed Periods:',''),
  array('No Periods Deleted',''),
  array('Has no slots',''),
  array('No slots Found Please restart the page',''),
  array('Not all slots Deleted unkown error',''),
  array('Action On Slot: successfully Removed Slot With Index:',''),
  array('Total removed Slots:',''),
  array('No Slots To deleted Please restart the page',''),
  array('Action On Period: successfully Removed Style Rule With Title:',''),
  array('Could not remove custom style with title:',''),
  array('title',''),
  array('To calendar With ID',''),
  array('Removed Style Rule With Title:',''),
  array('successfully Style Rule With Title:',''),
  array('Could not',''),
  array('custom style with title:',''),
  array('can not set the rule as empty Please remove it instead',''),
  array('Action On Periods: successfully edited Style Rule With Title:',''),
  array('Action On Periods: Could not edit custom style with title:',''),
  array('make sure it valid css',''),
  array('Action On Slots: successfully edited Style Rule With Title:',''),
  array('Action On Slots: Could not edit custom style with title:',''),
  array('Period Style rule group could not add missing required data',''),
  array('Action On Periods: successfully Add Custom Style Rule With Title:',''),
  array('total effected:',''),
  array('Action On Slots: successfully Add Custom Style Rule With Title:',''),
  array('Period main styles not edited due to missing required data',''),
  array('Slot main styles not edited due to missing required data',''),
  array('Action On Slots: successfully edited Main Style Total Changes On:',''),
  array('Style rules',''),
  array('Action On Slots: Could not edit Main style',''),
  array('Missing calendar id',''),
  array('calendar not found',''),
  array('is not valid calendar id',''),
  array('Missing Required Data can not update slot (period index or slot index or calendar id)',''),
  array('Updated Slot',''),
  array('Unkown error could not Update Slot',''),
  array('Missing Required Data can not update slot','')
);






function toLowerSingleVal($value) {
    return strtolower($value);
}





function in_array_r($needle, $haystack, $strict = false, $lang='') {
    $lang_index = $lang == 'english' ? 0 : 1;

    for ($i=0; $i<count($haystack); $i++) {
        $yourArray = array_map('toLowerSingleVal', $haystack[$i]);
        if (($strict ? $yourArray === strtolower($needle) : $yourArray == strtolower($needle)) || (is_array($yourArray) && in_array(strtolower($needle), $yourArray, $strict))) {


                if (count($yourArray) > $lang_index){
                  return $haystack[$i][$lang_index] ? $haystack[$i][$lang_index] : $needle;
                } else {
                  return $needle;
                }
    }
}
    return $needle;
}



function translate($needle, $lang='italian'){
  if ($lang != 'italian'){
	// now u can pass session value if u pass lang direct to function for example word always be itilian or english
    return in_array_r($needle, $GLOBALS['app_dictionary'], false, 'english');
  } else {
    return in_array_r($needle, $GLOBALS['app_dictionary'], false, 'english');
  }

}
echo translate('friday');

?>


</body>
</html>
